version: '3.7'
services: 
    php:
        build: 
            context: ./..
            dockerfile: docker/php/Dockerfile
        restart: always
        networks: 
            - glo-net
        volumes: 
            - ../app:/app

    web:
        build:
            context: ./..
            dockerfile: docker/nginx/Dockerfile
        restart: always
        ports:
            - '8081:8081'
        networks: 
            - glo-net
        volumes: 
            - ../app:/app
              

    db:
        build: 
            context: ./..
            dockerfile: docker/db/Dockerfile
        restart: always
        networks: 
            - glo-net
        ports: 
            - '5432:5432'
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}


    adminer:
        build:
            context: ./..
            dockerfile: docker/adminer/Dockerfile
        restart: always
        ports:
            - 8080:8080
        networks: 
            - glo-net

networks: 
    glo-net:

